### ISSUE TITLE
GlslViewer glslEditor glslCanvas 

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [terkelg/awesome-creative-coding#28]
GlslEditor is an online shader editor with some tools for life coding, recording, tweaking, testing  and sharing frag shaders http://editor.thebookofshaders.com code: https://github.com/patriciogonzalezvivo/glslEditor

GlslViewer is the openGL ES Shader renderer, have the same spec than glslEditor and can be run in MacOS, Linux and even raspberryPI directly from console. Code: http://github.com/patriciogonzalezvivo/glslViewer

Both are part of http://thebookofshaders.com specs and I use them together with glslCanvas to teach and sketch shaders.

In the same line I started a new project related to glsl shaders call phttp://ixelspiritdeck.com is a tangible glsl library on the back of tarot cards. Beside having it's own progression also present useful functions

**Comment by terkelg** [comment]
**Hi Patricio!**
First of all thanks for your amazing community work. I look up The Book of Shaders on a daily basis.

Both _The Book of Shaders_ and _GlslEditor_ are already a part of the list.
Let me know if you want changes to the copy or feel free to do a PR with the copy you want.

Can you make a PR for _GlslViewer_ and _PixelSpirit_? They are not on the list, but should definitely be there. Otherwise I have time to add them this weekend.

Btw, I love my Pixel Spirit deck. Keep up the good work 💯 
![img_3721](https://user-images.githubusercontent.com/2302254/29650218-4be853d6-884e-11e7-9423-16499779dfae.JPG)

**Comment by terkelg** [comment]
Resources are now added to the list
